version: "3"
services:
  app:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
        - ../..:/var/www/html
    environment:
      XDEBUG_EXTENSION_DEBUG: 1
      XDEBUG_CONFIG: "remote_host=172.17.0.1 remote_port=9001 remote_autostart=1"
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
