POST http://kissj.local/v3/deal/
Content-Type: application/json
Authorization: Bearer authtoken

{
	"TIE code": "YTCWVS",
	"jaká je to otázka?": "Možnost 1",
	"slug": "sfh"
}

###

POST http://kissj.local/v3/deal/
Content-Type: application/json
Authorization: Bearer authtoken

{
	"TIE code wrongly named, thus effectively missing": "YTCWVS",
	"jaká je to otázka?": "Možnost 1",
	"slug": "sfh"
}

###

POST http://kissj.local/v3/deal/
Content-Type: application/json
Authorization: Bearer authtoken

{"TIE code":"YTCWVS","Jak se chovat?":"Zodpovědně","Jak se nechovat?":"Nezodpovědně","slug":"sfh","enoughPoints":true}
###
