; load the opcache extension
zend_extension=opcache
; Enable OPCache
opcache.enable=1

; Allocate 256MB of memory for OPCache
opcache.memory_consumption=256
opcache.interned_strings_buffer=16

; Cache up to 20,000 PHP files
opcache.max_accelerated_files=20000

; Revalidate timestamps, dev environment uses this image with bind-mounted code
opcache.validate_timestamps=1
opcache.revalidate_freq=2
