FROM registry.access.redhat.com/ubi9/ubi:latest
LABEL maintainers "Kissj devs <https://github.com/SkautDevs>"

WORKDIR /var/www/html

#enable needed epel & remi repos
RUN dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm https://rpms.remirepo.net/enterprise/remi-release-9.rpm -y

#enable php81 module and install php
RUN dnf module enable php:remi-8.2 -y
RUN dnf install php-fpm php-cli composer php-pgsql php-pdo php-gd php-soap php-opcache unzip vim -y

#cleanup dnf cache
RUN dnf clean all

#copy app
COPY ./composer.json /var/www/html/composer.json
COPY ./composer.lock /var/www/html/composer.lock
COPY ./src /var/www/html/src
COPY ./public /var/www/html/public

#copy php config
COPY ./deploy/container_images/php/php.ini /etc/php.ini
COPY ./deploy/container_images/php/php-fpm.conf /etc/php-fpm.conf
COPY ./deploy/container_images/php/www.conf /etc/php-fpm.d/www.conf

#add user
RUN groupadd -g 1001 www-data
RUN useradd -u 1001 -g 1001 www-data -s /sbin/nologin -d /var/www/html -M
RUN chown -R www-data:www-data /var/lib/php 

#Create dummy .env
RUN touch /var/www/html/.env

#install deps
RUN composer install --working-dir=/var/www/html --no-dev --no-interaction --ignore-platform-req=ext-sqlite3

RUN chown -R www-data:www-data /var/www/html 

USER www-data
STOPSIGNAL SIGQUIT
EXPOSE 9000
CMD ["php-fpm", "-F"]