FROM php:8.0-fpm-buster

LABEL maintainer "Michael Kaplan <michael@kaplan.sh>"

WORKDIR /var/www/html

RUN apt update && apt install -y \
    curl \
    git \
    tar \
    zip \
    tzdata \
    libpq-dev \
    zlib1g-dev \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    vim

RUN apt-get clean
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer


RUN docker-php-ext-install \
    gd \
    pdo \
    pdo_pgsql \
    pgsql


COPY kissj-app/composer.json /var/www/html/composer.json
COPY kissj-app/composer.lock /var/www/html/composer.lock
COPY kissj-app/src /var/www/html/src
COPY kissj-app/adminer /var/www/html/adminer
COPY kissj-app/public /var/www/html/public

#Create dummy .env
RUN touch /var/www/html/.env

#create prod config
RUN cp /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini

#increse memory limit
RUN sed -i '/memory_limit/ s/128/512/' /usr/local/etc/php/php.ini

#change variable ordeiring at startup
RUN sed -i '/variables_order/ s/"GPCS"/"EGPCS"/' /usr/local/etc/php/php.ini

#allow env variable access
RUN sed -i 's\;clear_env = no\clear_env = no\' /usr/local/etc/php-fpm.d/www.conf

#export metrics
RUN sed -i 's\;pm.status_path = /status\pm.status_path = /status\' /usr/local/etc/php-fpm.d/www.conf

# increse max pool max_children
RUN sed -i '/pm.max_children/ s/5/20/' /usr/local/etc/php-fpm.d/www.conf

#install deps
RUN composer install --working-dir=/var/www/html --no-dev --no-interaction 

RUN chown -R www-data:www-data /var/www/html
