<?php

declare(strict_types=1);

namespace kissj\Event\EventType\Jj;

use kissj\Application\DateTimeUtils;
use kissj\Event\ContentArbiterGuest;
use kissj\Event\ContentArbiterIst;
use kissj\Event\ContentArbiterPatrolLeader;
use kissj\Event\ContentArbiterPatrolParticipant;
use kissj\Event\EventType\EventType;
use kissj\Participant\Ist\Ist;
use kissj\Participant\Participant;
use kissj\Participant\Patrol\PatrolLeader;

class EventTypeJj extends EventType
{
    protected function getPrice(Participant $participant): int
    {
        #TODO šátek
        return match (true) {
            $participant instanceof Ist => 300,
            $participant instanceof PatrolLeader => ($participant->getPatrolParticipantsCount() + 1) * 650,
            default => throw new \Exception('Unknown participant class'),
        };
    }

    public function getContentArbiterIst(): ContentArbiterIst
    {
        $caIst = parent::getContentArbiterIst();
#TODO

        return $caIst;
    }

    public function getContentArbiterPatrolLeader(): ContentArbiterPatrolLeader
    {
        $caPl = parent::getContentArbiterPatrolLeader();
#TODO

        return $caPl;
    }

    public function getContentArbiterPatrolParticipant(): ContentArbiterPatrolParticipant
    {
        $caPp = parent::getContentArbiterPatrolParticipant();
#TODO

        return $caPp;
    }

    public function getContentArbiterGuest(): ContentArbiterGuest
    {
        #TODO
        return parent::getContentArbiterGuest(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getTranslationFilePaths(): array
    {
        return [
            'cs' => __DIR__ . '/cs_jj.yaml',
        ];
    }

    #[\Override]
    public function getStylesheetNameWithoutLeadingSlash(): string
    {
        return 'eventSpecificCss/stylesJj25.css';
    }

    /**
     * @inheritDoc
     */
    public function getFoodOptions(): array
    {
        return [
            'detail.foodWithout',
            'detail.foodVegetarian',
            'detail.foodVegan',
            'detail.foodLactoseFree',
            'detail.foodGlutenFree',
            'detail.foodOther',
        ];
    }

    /**
     * @inheritDoc
     */
    public function getPositionOptions(): array
    {
        return [#TODO
            'detail.position.registration',
            'detail.position.kitchen',
            'detail.position.hygiene',
            'detail.position.site',
            'detail.position.security',
            'detail.position.programme',
        ];
    }

    /**
     * @inheritDoc
     */
    #[\Override]
    public function getLanguages(): array
    {
        return [
            'cs' => '🇨🇿 Česky',
        ];
    }

    public function isLoginSkautisAllowed(): bool
    {
        return true;
    }

    #[\Override]
    public function isReceiptAllowed(): bool
    {
        return true;
    }
}
