<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>CEJ 2018 Registrace</title>
    </head>
    <body>
        <h1>Registrace účastníka na CEJ 2018</h1>

        <form action="<?= $router->pathFor('signup'); ?>" method="post">
            <input type="email" name="email" placeholder="E-mail" required="required"/><br/>
            <input type="submit" value="Přihlásit se" />
        </form>
    </body>
</html>
