# .github/workflows/build.yml
name: Build & Push Container Images

on:
  workflow_call:
    inputs:
      envName:
        description: 'Environment to deploy to'
        required: true
        type: string
        default: staging

    secrets:
      REGISTRY_USER:
        description: 'Username for the registry'
        required: true
      
      REGISTRY_PASSWORD:
        description: 'Password for the registry'
        required: true
      

jobs:
  
  build-php:
    name: Build & Push PHP Container Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Build Container Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          layers: true
          oci: true
          image: php-ubi
          tags: ${{ inputs.envName}}-${{ github.sha }} latest
          containerfiles: |
            ./deploy/container_images/php/Containerfile-ubi
        
      - name: Push Container Image To Registry
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }} latest
          registry: quay.io/kissj
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}


  build-caddy:
    name: Build & Push Caddy container
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Build Container Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          layers: true
          oci: true
          image: caddy-ubi
          tags: ${{ inputs.envName}}-${{ github.sha }} latest
          containerfiles: |
            ./deploy/container_images/caddy/Containerfile-ubi
        
      - name: Push Container Image To Registry
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }} latest
          registry: quay.io/kissj
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}