name: Run Tests

on:
  workflow_call:
    

jobs:
  deps:
    name: Install & Cache Dependencies

    runs-on: ubuntu-latest
    container: docker.io/composer/composer:2.2.12

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      id: composer-validation
      run: composer validate --strict --no-interaction
      env:
        COMPOSER_ALLOW_SUPERUSER: 1

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
      
    - name: Install Dependencies
      id: composer-deps
      run: composer install --no-interaction --ignore-platform-req=ext-gd --ignore-platform-req=sqlite3
      env:
        COMPOSER_ALLOW_SUPERUSER: 1

    - name: Create workdir tarball
      run: tar -czpf /tmp/workdir.tgz . 
    
    - name: Upload workdir tarball
      uses: actions/upload-artifact@v3
      with:
        name: workdir
        path: /tmp/workdir.tgz


  stan:
    name: Static Analysis
    runs-on: ubuntu-latest
    container: docker.io/composer/composer:2.2.12
    needs: deps
    steps:

      - name: Download workdir tarball
        uses: actions/download-artifact@v3
        with:
          name: workdir
          path: .

      - name: Unpack workdir tarball 
        run: tar -xzf workdir.tgz 

      - name: stan
        continue-on-error: true
        run: composer run-script stan --no-interaction
        env:
          COMPOSER_ALLOW_SUPERUSER: 1
 

  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    container: docker.io/composer/composer:2.2.12
    needs: deps
    steps:

      - name: Download workdir tarball
        uses: actions/download-artifact@v3
        with:
          name: workdir
          path: .
          
      - name: Unpack workdir tarball 
        run: tar -xzf workdir.tgz 

      - name: unit 
        continue-on-error: true
        run: composer run-script unit --no-interaction
        env:
          COMPOSER_ALLOW_SUPERUSER: 1
 
  lint: 
    name: Check PHP syntax
    runs-on: ubuntu-latest
    container: docker.io/composer/composer:2.2.12
    needs: deps
    steps:
    
      - name: Check PHP syntax errors
        continue-on-error: true
        uses: overtrue/phplint@5.1.0
        with:
          path: /github/workflows
          options: --exclude=vendor --warning
  
#  cs: 
#    name: CodeSniffer 
#    runs-on: ubuntu-latest
#    container: docker.io/composer/composer:2.2.12
#    needs: deps
#    steps:
#
#      - name: Download workdir tarball
#        uses: actions/download-artifact@v3
#        with:
#          name: workdir
#          path: .
#          
#      - name: Unpack workdir tarball 
#        run: tar -xzf workdir.tgz 
#
#      - name: cs 
#        run: composer run-script cs --no-interaction
#        env:
#          COMPOSER_ALLOW_SUPERUSER: 1 