{{- if .Values.caddy.hpa.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-caddy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-caddy
  minReplicas: {{ .Values.caddy.hpa.minReplicas }}
  maxReplicas: {{ .Values.caddy.hpa.maxReplicas }}
  targetCPUUtilizationPercentage: 80
{{- end }}
---
{{- if .Values.php.hpa.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-php-fpm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-php-fpm
  minReplicas: {{ .Values.php.hpa.minReplicas }}
  maxReplicas: {{ .Values.php.hpa.maxReplicas }}
  targetCPUUtilizationPercentage: 80
{{- end }}