{{- if .Values.caddy.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-caddy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-caddy
  minReplicas: {{ .Values.caddy.hpa.minReplicas }}
  maxReplicas: {{ .Values.caddy.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageValue: 400Mi
  behavior:
    scaleUp:
      policies:
        - type: Pods
          value: 1
          periodSeconds: 10
      selectPolicy: Max
      stabilizationWindowSeconds: 10
    scaleDown:
      policies:
        - type: Pods
          value: 1
          periodSeconds: 10
      selectPolicy: Max
      stabilizationWindowSeconds: 30
{{- end }}
---
{{- if .Values.php.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-php-fpm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-php-fpm
  minReplicas: {{ .Values.php.hpa.minReplicas }}
  maxReplicas: {{ .Values.php.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageValue: 800Mi
  behavior:
    scaleUp:
      policies:
        - type: Pods
          value: 3
          periodSeconds: 10
        - type: Percent
          value: 30
          periodSeconds: 10
      selectPolicy: Max
      stabilizationWindowSeconds: 10
    scaleDown:
      policies:
        - type: Pods
          value: 2
          periodSeconds: 10
        - type: Percent
          value: 15
          periodSeconds: 10
      selectPolicy: Max
      stabilizationWindowSeconds: 30
{{- end }}