apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name}}-caddy-config
data:
    Caddyfile: |
        :8080 {
        	root * /var/www/html/public
        	file_server
        	php_fastcgi {env.PHPFPM_HOST}:9000
        	try_files {path} /index.php

        	log {
        		output stdout
        	}

          header {
            Strict-Transport-Security: max-age=31536000;
            X-Frame-Options DENY
            X-Content-Type-Options nosniff
            Referrer-Policy: no-referrer-when-downgrade
            Permission-Policy: '*' 'none'

            -Server
            -x-powered-by
          }
        
        }
        :9253 {
          metrics /metrics
        }

        :8000 {
          respond /healthz 200
        }

        