apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-pgbouncer
  labels:
    app.kubernetes.io/name: {{ .Chart.Name}}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: pgbouncer
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: pgbouncer
  template:
    metadata:
      labels:
        app.kubernetes.io/component: pgbouncer
    spec:
      containers:
      - name: pgbouncer
        image: bitnami/pgbouncer:latest
        imagePullPolicy: IfNotPresent
        env:
          #Define the environment variable
          - name: POSTGRESQL_HOST
            value: {{ .Values.postgres.host }}
          - name: POSTGRESQL_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-postgres
                key: username

          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-postgres
                key: password

          - name: POSTGRESQL_DATABASE
            value: {{ .Values.postgres.dbname }}


          - name: PGBOUNCER_PORT
            value: "5432"
          - name: PGBOUNCER_MAX_CLIENT_CONN
            value: "1500"
          - name: PGBOUNCER_MAX_DB_CONNECTIONS
            value: "50" 
          - name: PGBOUNCER_DATABASE
            value: {{ .Values.postgres.dbname }}
                 
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "600m"
        ports:
        - containerPort: 5432

        volumeMounts:
        - mountPath: /etc/pgbouncer/ca
          name: {{ .Release.Name}}-pgbouncer-ca
      volumes:
      - name: {{ .Release.Name}}-pgbouncer-ca
        secret:
          secretName: {{ .Release.Name}}-pgbouncer-ca