apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres
type: Opaque
stringData:
  username: {{ .Values.postgres.username | quote }}
  password: {{ .Values.postgres.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-s3
type: Opaque
stringData:
  key: {{ .Values.app.s3.key | quote }}
  secret: {{ .Values.app.s3.secret | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mail
type: Opaque
stringData:
  username: {{ .Values.app.mail.username | quote }}
  password: {{ .Values.app.mail.password | quote }}
  dsn: {{ .Values.app.mail.dsn | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-sentry-dsn
type: Opaque
stringData:
  dsn: {{ .Values.app.sentry.dsn | quote}}
  profiling_rate: {{ .Values.app.sentry.profiling_rate | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-skautis
type: Opaque
stringData:
  appId: {{ .Values.app.skautis.appId | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-redis-creds
type: Opaque
stringData:
  password: {{ .Values.app.redis.password | quote }}